# Generated by Django 4.1 on 2022-09-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
