# Generated by Django 4.1 on 2022-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_email_alter_user_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(default=' '),
        ),
    ]
