# Generated by Django 4.1 on 2022-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='tehran', max_length=200, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, default=' ', verbose_name='گیتهاب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, default=' ', verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default=' ', verbose_name='وبسایت'),
        ),
    ]
