# Generated by Django 4.1 on 2022-09-16 08:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExprience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('start_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1380), django.core.validators.MaxValueValidator(1401)])),
                ('start_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('end_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1380), django.core.validators.MaxValueValidator(1401)])),
                ('end_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('description', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_work', to='resume.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.template'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.IntegerField(choices=[(1, 'ضعیف'), (2, 'متوسط'), (3, 'خوب'), (4, 'عالی')])),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_language', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('start_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1380), django.core.validators.MaxValueValidator(1401)])),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_education', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ability', to='resume.resume')),
            ],
        ),
    ]
