# Generated by Django 4.1 on 2022-09-24 18:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0002_education_end_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name': 'ability', 'verbose_name_plural': 'abilities'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'education', 'verbose_name_plural': 'educations'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'resume', 'verbose_name_plural': 'resumes'},
        ),
        migrations.AlterModelOptions(
            name='workexprience',
            options={'verbose_name': 'work experience', 'verbose_name_plural': 'work experiences'},
        ),
        migrations.AlterField(
            model_name='ability',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1380), django.core.validators.MaxValueValidator(1401)], verbose_name='سال پایان'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1380), django.core.validators.MaxValueValidator(1401)], verbose_name='سال شروع'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام محل تحصیل'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(choices=[(1, 'ضعیف'), (2, 'متوسط'), (3, 'خوب'), (4, 'عالی')], verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='workexprience',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='workexprience',
            name='end_month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه پایان'),
        ),
        migrations.AlterField(
            model_name='workexprience',
            name='end_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1380), django.core.validators.MaxValueValidator(1401)], verbose_name='سال پایان'),
        ),
        migrations.AlterField(
            model_name='workexprience',
            name='start_month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه شروع'),
        ),
        migrations.AlterField(
            model_name='workexprience',
            name='start_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1380), django.core.validators.MaxValueValidator(1401)], verbose_name='سال شروع'),
        ),
        migrations.AlterField(
            model_name='workexprience',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
