{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Users Abilties",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id), title FROM resume_ability GROUP BY title;"
    }
   ]
  },
  {
   "title": "User with completed Profile",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(is_complete) FROM account_user WHERE is_complete=True;\n"
    }
   ]
  },
  {
   "title": "Users City",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id), city FROM account_user GROUP BY city;"
    }
   ]
  },
  {
   "title": "Users Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM account_user LIMIT 50 "
    }
   ]
  }
 ]
}